### ISSUE TITLE
Publicatie aangepaste versie

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-bekistingsmateriaal#2]
de codelijst bekistingsmateriaal is goedgekeurd door OC-DOV (schriftelijk proces 07/06/2024) voor de publicatie van versie 1.
In attachment vind je versie 1 van deze codelijst met nog een aantal wijzigingen ten opzichte van de huidige codelijst:
Het doel van deze codelijst is het oplijsten van de verschillende soorten bekistingen waarmee een boorgat afgewerkt kan zijn. In overleg met de inhoudelijke aanspreekpunten werd de oorspronkelijke codelijst vereenvoudigd. Velden die niet onder bekisting vallen (zoals geen filterput aanwezig of straatpot) werden verwijderd. 

Eens de codelijst is geüpdatet kan het proces voor publicatie van de codelijst opgestart worden.
[codelijst-source.xlsx](https://github.com/user-attachments/files/15759694/codelijst-source.xlsx)

**Comment by debaetpa** [comment]
de ',,,' is vervangen door '…' (kwam 2x voor in prefLabel)
codelijst-source.csv is aangepast

definitions op niveau 'conceptscheme' of 'collectie' gaven foutmelding; die zijn dus weggelaten.

**Comment by debaetpa** [comment]
@ChandraAlgoe misschien moet toch iets anders dan 0 .. 4 gekozen worden?

xsd ziet er nu zo uit

      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/0" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/1" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/2" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/3" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/4" />

**Comment by ChandraAlgoe** [comment]
aangepast voorstel toegevoegd in bijlage: [codelijst-source.xlsx](https://github.com/user-attachments/files/15799997/codelijst-source.xlsx)

concept:natuurlijk
concept:kunstofPVC
concept:kunstofander
concept:metaal
concept:steen

**Comment by debaetpa** [comment]
aangepast, nog 2 schrijffouten: 
kunststofPVC (ipv kunstofPVC)
kunststofander (ipv kunstofander)

**Comment by debaetpa** [comment]
is veel leesbaarder nu:
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/kunststofPVC" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/kunststofander" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/metaal" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/natuurlijk" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/bekistingsmateriaal/steen" />
